######################################################################
##
## Filename: tb_counter.udo
## Created on: Tue Sep 23 09:40:36 PM CDT 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
