######################################################################
##
## Filename: tb_filter.udo
## Created on: Tue Sep 23 11:02:58 PM CDT 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
