######################################################################
##
## Filename: tb_generate_ppm.udo
## Created on: Wed Sep 24 04:22:23 PM CDT 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
