######################################################################
##
## Filename: tb_temp_register.udo
## Created on: Wed Sep 24 05:41:53 PM CDT 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
